In [2]:
import fastf1
import pandas as pd
import numpy
import pyarrow as pa
import pyarrow.parquet as pq

In [3]:
fastf1.Cache.enable_cache('/Users/dimkostir/Desktop/Projects/F1/data/raw/fastf1_cache')

In [6]:
fp2 = fastf1.get_session(2026, 1, 'FP2')
fp2.load()
fp2_laps = fp2.laps  # ← αυτό θέλεις
fp2_laps

core           INFO 	Loading data for Australian Grand Prix - Practice 2 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:14:55.294000,NOR,1,NaT,1.0,1.0,0 days 00:12:59.921000,NaT,NaT,0 days 00:00:23.001000,...,True,McLaren,0 days 00:12:59.921000,2026-03-06 05:00:12.101,1,NaN,False,,False,False
1,0 days 00:16:21.246000,NOR,1,0 days 00:01:25.952000,2.0,1.0,NaT,NaT,0 days 00:00:29.509000,0 days 00:00:18.380000,...,True,McLaren,0 days 00:14:55.294000,2026-03-06 05:02:07.474,12,NaN,False,,False,True
2,0 days 00:17:59.501000,NOR,1,0 days 00:01:38.255000,3.0,1.0,NaT,NaT,0 days 00:00:32.037000,0 days 00:00:19.145000,...,True,McLaren,0 days 00:16:21.246000,2026-03-06 05:03:33.426,1,NaN,False,,False,True
3,0 days 00:27:25.498000,NOR,1,NaT,4.0,1.0,NaT,0 days 00:20:17.780000,0 days 00:00:52.162000,0 days 00:00:32.327000,...,True,McLaren,0 days 00:17:59.501000,2026-03-06 05:05:11.681,1,NaN,False,,False,False
4,0 days 00:29:02.397000,NOR,1,0 days 00:01:36.899000,5.0,2.0,0 days 00:27:27.972000,NaT,0 days 00:00:36.873000,0 days 00:00:18.865000,...,False,McLaren,0 days 00:27:25.498000,2026-03-06 05:14:37.678,1,NaN,False,,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,0 days 01:10:35.170000,BEA,87,0 days 00:01:26,27.0,4.0,NaT,NaT,0 days 00:00:30.421000,0 days 00:00:18.081000,...,False,Haas F1 Team,0 days 01:09:09.170000,2026-03-06 05:56:21.350,1,NaN,False,,False,True
540,0 days 01:12:01.077000,BEA,87,0 days 00:01:25.907000,28.0,4.0,NaT,NaT,0 days 00:00:30.323000,0 days 00:00:18.208000,...,False,Haas F1 Team,0 days 01:10:35.170000,2026-03-06 05:57:47.350,1,NaN,False,,False,True
541,0 days 01:13:26.946000,BEA,87,0 days 00:01:25.869000,29.0,4.0,NaT,NaT,0 days 00:00:30.362000,0 days 00:00:18.116000,...,False,Haas F1 Team,0 days 01:12:01.077000,2026-03-06 05:59:13.257,1,NaN,False,,False,True
542,0 days 01:15:37.702000,BEA,87,0 days 00:02:10.756000,30.0,4.0,NaT,NaT,0 days 00:00:39.892000,0 days 00:00:28.496000,...,False,Haas F1 Team,0 days 01:13:26.946000,2026-03-06 06:00:39.126,1,NaN,False,,False,True
543,0 days 01:17:26.353000,BEA,87,NaT,31.0,4.0,NaT,0 days 01:17:26.353000,0 days 00:00:51.309000,0 days 00:00:18.668000,...,False,Haas F1 Team,0 days 01:15:37.702000,2026-03-06 06:02:49.882,1,NaN,False,,False,False

In [3]:
bah_res = fastf1.get_session(2026, 1, 'R')
bah_res.load()
bah_res = bah_res.results
bah_res['Time'].dtype
bah_res['Time'] = bah_res['Time'].dt.total_seconds()
bah_res = bah_res.drop(["DriverNumber", "DriverId", "HeadshotUrl", "TeamColor", "FirstName", "LastName", "BroadcastName", "Q1", "Q2", "Q3"], axis= 1)
bah_res.loc[bah_res['Position'] == 1, 'Time'] = 0
bah_res.to_csv('/Users/dimkostir/Desktop/Projects/F1/data/processed/results_r.csv')

bah_res

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

,Abbreviation,TeamName,TeamId,FullName,CountryCode,Position,ClassifiedPosition,GridPosition,Time,Status,Points,Laps
63,RUS,Mercedes,mercedes,George Russell,,1.0,1,1.0,0.000,Finished,25.0,58.0
12,ANT,Mercedes,mercedes,Kimi Antonelli,,2.0,2,2.0,2.974,Finished,18.0,58.0
16,LEC,Ferrari,ferrari,Charles Leclerc,,3.0,3,4.0,15.519,Finished,15.0,58.0
44,HAM,Ferrari,ferrari,Lewis Hamilton,,4.0,4,7.0,16.144,Finished,12.0,58.0
1,NOR,McLaren,mclaren,Lando Norris,,5.0,5,6.0,51.741,Finished,10.0,58.0
3,VER,Red Bull Racing,red_bull,Max Verstappen,,6.0,6,20.0,54.617,Finished,8.0,58.0
87,BEA,Haas F1 Team,haas,Oliver Bearman,,7.0,7,12.0,4.593,Lapped,6.0,57.0
41,LIN,Racing Bulls,rb,Arvid Lindblad,,8.0,8,9.0,11.816,Lapped,4.0,57.0
5,BOR,Audi,audi,Gabriel Bortoleto,,9.0,9,10.0,12.775,Lapped,2.0,57.0
10,GAS,Alpine,alpine,Pierre Gasly,,10.0,10,14.0,29.027,Lapped,1.0,57.0
31,OCO,Haas F1 Team,haas,Esteban Ocon,,11.0,11,13.0,29.850,Lapped,0.0,57.0
23,ALB,Williams,williams,Alexander Albon,,12.0,12,15.0,56.075,Lapped,0.0,57.0
30,LAW,Racing Bulls,rb,Liam Lawson,,13.0,13,8.0,57.173,Lapped,0.0,57.0
43,COL,Alpine,alpine,Franco Colapinto,,14.0,14,16.0,8.487,Lapped,0.0,56.0
55,SAI,Williams,williams,Carlos Sainz,,15.0,15,21.0,36.886,Lapped,0.0,56.0
11,PER,Cadillac,cadillac,Sergio Perez,,16.0,16,18.0,7.850,Lapped,0.0,55.0
18,STR,Aston Martin,aston_martin,Lance Stroll,,17.0,R,22.0,NaN,Lapped,0.0,43.0
14,ALO,Aston Martin,aston_martin,Fernando Alonso,,18.0,R,17.0,NaN,Retired,0.0,21.0
77,BOT,Cadillac,cadillac,Valtteri Bottas,,19.0,R,19.0,NaN,Retired,0.0,15.0
6,HAD,Red Bull Racing,red_bull,Isack Hadjar,,20.0,R,3.0,NaN,Retired,0.0,10.0
81,PIA,McLaren,mclaren,Oscar Piastri,,21.0,W,5.0,NaN,Did not start,0.0,0.0
27,HUL,Audi,audi,Nico Hulkenberg,,22.0,W,11.0,NaN,Did not start,0.0,0.0

In [56]:
q_laps = fastf1.get_session(2026, 1, 'Q')
q_laps.load()
q_laps = q_laps.laps
q_laps = q_laps.drop(["LapStartDate"], axis = 1)
q_laps['Time'] = q_laps['Time'].dt.total_seconds()
q_laps['LapTime'] = q_laps['LapTime'].dt.total_seconds()
q_laps['PitOutTime'] = q_laps['PitOutTime'].dt.total_seconds()
q_laps['PitInTime'] = q_laps['PitInTime'].dt.total_seconds()
q_laps['LapStartTime'] = q_laps['LapStartTime'].dt.total_seconds()
q_laps['Sector1Time'] = q_laps['Sector1Time'].dt.total_seconds()
q_laps['Sector2Time'] = q_laps['Sector2Time'].dt.total_seconds()
q_laps['Sector3Time'] = q_laps['Sector3Time'].dt.total_seconds()

q_laps['Sector1SessionTime'] = q_laps['Sector1SessionTime'].dt.total_seconds()
q_laps['Sector2SessionTime'] = q_laps['Sector2SessionTime'].dt.total_seconds()
q_laps['Sector3SessionTime'] = q_laps['Sector3SessionTime'].dt.total_seconds()

for x in q_laps.index:
  if q_laps.loc[x, "IsAccurate"] == False:
    q_laps.drop(x, inplace = True)

q_laps.to_csv('/Users/dimkostir/Desktop/Projects/F1/data/processed/q_laps.csv')
q_laps.to_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/q_laps.parquet')

q_laps

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	No lap data for driver 55
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '6', '16', '81', '1', '44', '30', '41', '5', '27', '87', '31', '10', '23', '43', '14', '11', '77', '18', '3', '55']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TyreLife,FreshTyre,Team,LapStartTime,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
1,1177.291,RUS,63,79.840,2.0,1.0,NaN,NaN,27.990,17.599,...,2.0,True,Mercedes,1097.451,1,NaN,False,,False,True
5,2125.609,RUS,63,93.246,6.0,3.0,NaN,NaN,31.116,23.100,...,6.0,False,Mercedes,2032.363,1,NaN,False,,False,True
6,2205.116,RUS,63,79.507,7.0,3.0,NaN,NaN,27.908,17.413,...,7.0,False,Mercedes,2125.609,1,NaN,False,,False,True
9,3109.517,RUS,63,78.934,10.0,4.0,NaN,NaN,27.816,17.287,...,2.0,True,Mercedes,3030.583,1,NaN,False,,False,True
12,3546.975,RUS,63,78.987,13.0,5.0,NaN,NaN,27.662,17.426,...,5.0,False,Mercedes,3467.988,1,NaN,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,2332.857,ALO,14,81.969,9.0,2.0,NaN,NaN,28.797,18.047,...,4.0,True,Aston Martin,2250.888,1,NaN,False,,False,True
337,1034.061,PER,11,83.567,2.0,1.0,NaN,NaN,29.434,17.996,...,2.0,True,Cadillac,950.494,1,NaN,False,,False,True
341,2349.261,PER,11,82.605,6.0,3.0,NaN,NaN,29.138,17.819,...,2.0,True,Cadillac,2266.656,1,NaN,False,,False,True
344,1038.557,BOT,77,83.641,2.0,1.0,NaN,NaN,29.482,17.949,...,2.0,True,Cadillac,954.916,1,NaN,False,,False,True
349,2344.074,BOT,77,83.244,7.0,3.0,NaN,NaN,29.198,18.068,...,2.0,True,Cadillac,2260.830,1,NaN,False,,False,True

In [15]:
bah_res.to_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/results_r.parquet')

In [44]:
r_laps = fastf1.get_session(2026, 1, 'R')
r_laps.load()
r_laps = r_laps.laps

r_laps['Time'] = r_laps['Time'].dt.total_seconds()
r_laps['LapTime'] = r_laps['LapTime'].dt.total_seconds()
r_laps['LapStartTime'] = r_laps['LapStartTime'].dt.total_seconds()
r_laps['Sector1Time'] = r_laps['Sector1Time'].dt.total_seconds()
r_laps['Sector2Time'] = r_laps['Sector2Time'].dt.total_seconds()
r_laps['Sector3Time'] = r_laps['Sector3Time'].dt.total_seconds()
r_laps['Sector1SessionTime'] = r_laps['Sector1SessionTime'].dt.total_seconds()
r_laps['Sector2SessionTime'] = r_laps['Sector2SessionTime'].dt.total_seconds()
r_laps['Sector3SessionTime'] = r_laps['Sector3SessionTime'].dt.total_seconds()
r_laps['PitOutTime'] = r_laps['PitOutTime'].dt.total_seconds()
r_laps['PitInTime'] = r_laps['PitInTime'].dt.total_seconds()

r_laps.to_csv('/Users/dimkostir/Desktop/Projects/F1/data/processed/r_laps.csv')
r_laps

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,3836.437,NOR,1,96.458,1.0,1.0,NaN,NaN,NaN,18.163,...,True,McLaren,3739.743,2026-03-08 04:03:26.366,1,6.0,False,,False,False
1,3923.781,NOR,1,87.344,2.0,1.0,NaN,NaN,31.074,18.116,...,True,McLaren,3836.437,2026-03-08 04:05:03.060,1,6.0,False,,False,True
2,4010.644,NOR,1,86.863,3.0,1.0,NaN,NaN,30.541,18.252,...,True,McLaren,3923.781,2026-03-08 04:06:30.404,1,7.0,False,,False,True
3,4096.501,NOR,1,85.857,4.0,1.0,NaN,NaN,30.190,18.193,...,True,McLaren,4010.644,2026-03-08 04:07:57.267,1,7.0,False,,False,True
4,4182.074,NOR,1,85.573,5.0,1.0,NaN,NaN,29.930,17.868,...,True,McLaren,4096.501,2026-03-08 04:09:23.124,1,7.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,8389.241,BEA,87,84.615,53.0,2.0,NaN,NaN,29.699,17.937,...,True,Haas F1 Team,8304.626,2026-03-08 05:19:31.249,1,7.0,False,,False,True
1003,8473.851,BEA,87,84.610,54.0,2.0,NaN,NaN,29.965,17.876,...,True,Haas F1 Team,8389.241,2026-03-08 05:20:55.864,1,7.0,False,,False,True
1004,8558.351,BEA,87,84.500,55.0,2.0,NaN,NaN,29.725,17.930,...,True,Haas F1 Team,8473.851,2026-03-08 05:22:20.474,1,7.0,False,,False,True
1005,8644.790,BEA,87,86.439,56.0,2.0,NaN,NaN,29.768,17.858,...,True,Haas F1 Team,8558.351,2026-03-08 05:23:44.974,1,7.0,False,,False,True
1006,8731.439,BEA,87,86.649,57.0,2.0,NaN,NaN,30.005,17.905,...,True,Haas F1 Team,8644.790,2026-03-08 05:25:11.413,1,7.0,False,,False,True

In [55]:
q_results = fastf1.get_session(2026, 1, 'Q')
q_results.load()
q_results = q_results.results
q_results = q_results.drop(["HeadshotUrl", "Points", "Laps", "GridPosition", "Status", "Points", "Laps","TeamColor", "DriverNumber"], axis= 1)
q_results["Q1"] = q_results["Q1"].dt.total_seconds()
q_results["Q2"] = q_results["Q2"].dt.total_seconds()
q_results["Q3"] = q_results["Q3"].dt.total_seconds()
q_results.to_csv('/Users/dimkostir/Desktop/Projects/F1/data/processed/q_results.csv')
q_results.to_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/q_results.parquet')
q_results

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	No lap data for driver 55
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '6', '16', '81', '1', '44', '30', '41', '5', '27', '87', '31', '10', '23', '43', '14', '11', '77', '18', '3', '55']

,BroadcastName,Abbreviation,DriverId,TeamName,TeamId,FirstName,LastName,FullName,CountryCode,Position,ClassifiedPosition,Q1,Q2,Q3,Time
63,G RUSSELL,RUS,russell,Mercedes,mercedes,George,Russell,George Russell,,1.0,,79.507,78.934,78.518,NaT
12,K ANTONELLI,ANT,antonelli,Mercedes,mercedes,Kimi,Antonelli,Kimi Antonelli,,2.0,,80.120,79.435,78.811,NaT
6,I HADJAR,HAD,hadjar,Red Bull Racing,red_bull,Isack,Hadjar,Isack Hadjar,,3.0,,80.023,79.653,79.303,NaT
16,C LECLERC,LEC,leclerc,Ferrari,ferrari,Charles,Leclerc,Charles Leclerc,,4.0,,80.226,79.357,79.327,NaT
81,O PIASTRI,PIA,piastri,McLaren,mclaren,Oscar,Piastri,Oscar Piastri,,5.0,,79.664,79.525,79.380,NaT
1,L NORRIS,NOR,norris,McLaren,mclaren,Lando,Norris,Lando Norris,,6.0,,80.010,79.882,79.475,NaT
44,L HAMILTON,HAM,hamilton,Ferrari,ferrari,Lewis,Hamilton,Lewis Hamilton,,7.0,,79.811,79.921,79.478,NaT
30,L LAWSON,LAW,lawson,Racing Bulls,rb,Liam,Lawson,Liam Lawson,,8.0,,80.491,80.144,79.994,NaT
41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,rb,Arvid,Lindblad,Arvid Lindblad,,9.0,,80.409,79.971,81.247,NaT
5,G BORTOLETO,BOR,bortoleto,Audi,audi,Gabriel,Bortoleto,Gabriel Bortoleto,,10.0,,80.495,80.221,NaN,NaT
27,N HULKENBERG,HUL,hulkenberg,Audi,audi,Nico,Hulkenberg,Nico Hulkenberg,,11.0,,81.024,80.303,NaN,NaT
87,O BEARMAN,BEA,bearman,Haas F1 Team,haas,Oliver,Bearman,Oliver Bearman,,12.0,,81.247,80.311,NaN,NaT
31,E OCON,OCO,ocon,Haas F1 Team,haas,Esteban,Ocon,Esteban Ocon,,13.0,,80.759,80.491,NaN,NaT
10,P GASLY,GAS,gasly,Alpine,alpine,Pierre,Gasly,Pierre Gasly,,14.0,,81.138,80.501,NaN,NaT
23,A ALBON,ALB,albon,Williams,williams,Alexander,Albon,Alexander Albon,,15.0,,81.051,80.941,NaN,NaT
43,F COLAPINTO,COL,colapinto,Alpine,alpine,Franco,Colapinto,Franco Colapinto,,16.0,,81.200,81.270,NaN,NaT
14,F ALONSO,ALO,alonso,Aston Martin,aston_martin,Fernando,Alonso,Fernando Alonso,,17.0,,81.969,NaN,NaN,NaT
11,S PEREZ,PER,perez,Cadillac,cadillac,Sergio,Perez,Sergio Perez,,18.0,,82.605,NaN,NaN,NaT
77,V BOTTAS,BOT,bottas,Cadillac,cadillac,Valtteri,Bottas,Valtteri Bottas,,19.0,,83.244,NaN,NaN,NaT
18,L STROLL,STR,nan,Aston Martin,nan,Lance,Stroll,Lance Stroll,,NaN,,NaN,NaN,NaN,NaT
3,M VERSTAPPEN,VER,nan,Red Bull Racing,nan,Max,Verstappen,Max Verstappen,,NaN,,NaN,NaN,NaN,NaT
55,C SAINZ,SAI,nan,Williams,nan,Carlos,Sainz,Carlos Sainz,,NaN,,NaN,NaN,NaN,NaT

In [54]:
schedule_2026 = fastf1.get_events_remaining()
schedule_2026.to_csv('/Users/dimkostir/Desktop/Projects/F1/data/processed/schedule_2026.csv')
schedule_2026.to_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/schedule_2026.parquet')

In [ ]:
r_laps = fastf1.get_session(2026, 1, 'R')
r_laps.load()
r_laps = r_laps.laps

r_laps = r_laps[
    (r_laps["TrackStatus"] == "1") &
    (r_laps["LapTime"].notna()) &
    (r_laps["PitInTime"].isna()) &
    (r_laps["PitOutTime"].isna())
]
r_laps['Time'] = r_laps['Time'].dt.total_seconds()
r_laps['LapTime'] = r_laps['LapTime'].dt.total_seconds()
r_laps['LapStartTime'] = r_laps['LapStartTime'].dt.total_seconds()
r_laps['Sector1Time'] = r_laps['Sector1Time'].dt.total_seconds()
r_laps['Sector2Time'] = r_laps['Sector2Time'].dt.total_seconds()
r_laps['Sector3Time'] = r_laps['Sector3Time'].dt.total_seconds()
r_laps['Sector1SessionTime'] = r_laps['Sector1SessionTime'].dt.total_seconds()
r_laps['Sector2SessionTime'] = r_laps['Sector2SessionTime'].dt.total_seconds()
r_laps['Sector3SessionTime'] = r_laps['Sector3SessionTime'].dt.total_seconds()
r_laps = r_laps.drop(["PitInTime", "PitOutTime"], axis= 1)

r_laps.to_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/r_laps_clean.parquet')
r_laps

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['Time'] = r_laps['Time'].dt.total_seconds()
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['LapTime'] = r_laps['LapTime'].dt.total_seconds()
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['LapStartTime'] = r_laps['LapStartTime'].dt.total_seconds()
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['Sector1Time'] = r_laps['Sector1Time'].dt.total_seconds()
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['Sector2Time'] = r_laps['Sector2Time'].dt.total_seconds()
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['Sector3Time'] = r_laps['Sector3Time'].dt.total_seconds()
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['Sector1SessionTime'] = r_laps['Sector1SessionTime'].dt.total_seconds()
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['Sector2SessionTime'] = r_laps['Sector2SessionTime'].dt.total_seconds()
/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_7486/118132577.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_laps['Sector3SessionTime'] = r_laps['Sector3SessionTime'].dt.total_seconds()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,3836.437,NOR,1,96.458,1.0,1.0,NaN,18.163,38.796,NaN,...,True,McLaren,3739.743,2026-03-08 04:03:26.366,1,6.0,False,,False,False
1,3923.781,NOR,1,87.344,2.0,1.0,31.074,18.116,38.154,3867.511,...,True,McLaren,3836.437,2026-03-08 04:05:03.060,1,6.0,False,,False,True
2,4010.644,NOR,1,86.863,3.0,1.0,30.541,18.252,38.070,3954.322,...,True,McLaren,3923.781,2026-03-08 04:06:30.404,1,7.0,False,,False,True
3,4096.501,NOR,1,85.857,4.0,1.0,30.190,18.193,37.474,4040.834,...,True,McLaren,4010.644,2026-03-08 04:07:57.267,1,7.0,False,,False,True
4,4182.074,NOR,1,85.573,5.0,1.0,29.930,17.868,37.775,4126.431,...,True,McLaren,4096.501,2026-03-08 04:09:23.124,1,7.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,8389.241,BEA,87,84.615,53.0,2.0,29.699,17.937,36.979,8334.357,...,True,Haas F1 Team,8304.626,2026-03-08 05:19:31.249,1,7.0,False,,False,True
1003,8473.851,BEA,87,84.610,54.0,2.0,29.965,17.876,36.769,8419.238,...,True,Haas F1 Team,8389.241,2026-03-08 05:20:55.864,1,7.0,False,,False,True
1004,8558.351,BEA,87,84.500,55.0,2.0,29.725,17.930,36.845,8503.608,...,True,Haas F1 Team,8473.851,2026-03-08 05:22:20.474,1,7.0,False,,False,True
1005,8644.790,BEA,87,86.439,56.0,2.0,29.768,17.858,38.813,8588.151,...,True,Haas F1 Team,8558.351,2026-03-08 05:23:44.974,1,7.0,False,,False,True
1006,8731.439,BEA,87,86.649,57.0,2.0,30.005,17.905,38.739,8674.827,...,True,Haas F1 Team,8644.790,2026-03-08 05:25:11.413,1,7.0,False,,False,True