In [1]:
import fastf1
import pandas as pd
import numpy as np
import pyarrow
import pyarrow.parquet as pq
from scipy.stats import spearmanr

In [2]:
r_results = pd.read_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/results_r.parquet')
r_laps = pd.read_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/r_laps_clean.parquet')
schedule = pd.read_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/schedule_2026.parquet')
q_laps = pd.read_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/q_laps.parquet')
q_results = pd.read_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/q_results.parquet')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/dimkostir/Desktop/Projects/F1/data/processed/results_r.parquet'

In [4]:
q_results["Best_Q"] = q_results["Q3"].fillna(q_results["Q2"]).fillna(q_results["Q1"])
q_results

,BroadcastName,Abbreviation,DriverId,TeamName,TeamId,FirstName,LastName,FullName,CountryCode,Position,ClassifiedPosition,Q1,Q2,Q3,Time,Best_Q
63,G RUSSELL,RUS,russell,Mercedes,mercedes,George,Russell,George Russell,,1.0,,79.507,78.934,78.518,NaT,78.518
12,K ANTONELLI,ANT,antonelli,Mercedes,mercedes,Kimi,Antonelli,Kimi Antonelli,,2.0,,80.120,79.435,78.811,NaT,78.811
6,I HADJAR,HAD,hadjar,Red Bull Racing,red_bull,Isack,Hadjar,Isack Hadjar,,3.0,,80.023,79.653,79.303,NaT,79.303
16,C LECLERC,LEC,leclerc,Ferrari,ferrari,Charles,Leclerc,Charles Leclerc,,4.0,,80.226,79.357,79.327,NaT,79.327
81,O PIASTRI,PIA,piastri,McLaren,mclaren,Oscar,Piastri,Oscar Piastri,,5.0,,79.664,79.525,79.380,NaT,79.380
1,L NORRIS,NOR,norris,McLaren,mclaren,Lando,Norris,Lando Norris,,6.0,,80.010,79.882,79.475,NaT,79.475
44,L HAMILTON,HAM,hamilton,Ferrari,ferrari,Lewis,Hamilton,Lewis Hamilton,,7.0,,79.811,79.921,79.478,NaT,79.478
30,L LAWSON,LAW,lawson,Racing Bulls,rb,Liam,Lawson,Liam Lawson,,8.0,,80.491,80.144,79.994,NaT,79.994
41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,rb,Arvid,Lindblad,Arvid Lindblad,,9.0,,80.409,79.971,81.247,NaT,81.247
5,G BORTOLETO,BOR,bortoleto,Audi,audi,Gabriel,Bortoleto,Gabriel Bortoleto,,10.0,,80.495,80.221,NaN,NaT,80.221
27,N HULKENBERG,HUL,hulkenberg,Audi,audi,Nico,Hulkenberg,Nico Hulkenberg,,11.0,,81.024,80.303,NaN,NaT,80.303
87,O BEARMAN,BEA,bearman,Haas F1 Team,haas,Oliver,Bearman,Oliver Bearman,,12.0,,81.247,80.311,NaN,NaT,80.311
31,E OCON,OCO,ocon,Haas F1 Team,haas,Esteban,Ocon,Esteban Ocon,,13.0,,80.759,80.491,NaN,NaT,80.491
10,P GASLY,GAS,gasly,Alpine,alpine,Pierre,Gasly,Pierre Gasly,,14.0,,81.138,80.501,NaN,NaT,80.501
23,A ALBON,ALB,albon,Williams,williams,Alexander,Albon,Alexander Albon,,15.0,,81.051,80.941,NaN,NaT,80.941
43,F COLAPINTO,COL,colapinto,Alpine,alpine,Franco,Colapinto,Franco Colapinto,,16.0,,81.200,81.270,NaN,NaT,81.270
14,F ALONSO,ALO,alonso,Aston Martin,aston_martin,Fernando,Alonso,Fernando Alonso,,17.0,,81.969,NaN,NaN,NaT,81.969
11,S PEREZ,PER,perez,Cadillac,cadillac,Sergio,Perez,Sergio Perez,,18.0,,82.605,NaN,NaN,NaT,82.605
77,V BOTTAS,BOT,bottas,Cadillac,cadillac,Valtteri,Bottas,Valtteri Bottas,,19.0,,83.244,NaN,NaN,NaT,83.244
18,L STROLL,STR,nan,Aston Martin,nan,Lance,Stroll,Lance Stroll,,NaN,,NaN,NaN,NaN,NaT,NaN
3,M VERSTAPPEN,VER,nan,Red Bull Racing,nan,Max,Verstappen,Max Verstappen,,NaN,,NaN,NaN,NaN,NaT,NaN
55,C SAINZ,SAI,nan,Williams,nan,Carlos,Sainz,Carlos Sainz,,NaN,,NaN,NaN,NaN,NaT,NaN

In [5]:
best_q = q_results["Best_Q"].min()
best_q

q_results["delta_to_pole"] = q_results["Best_Q"] - best_q
q_results

,BroadcastName,Abbreviation,DriverId,TeamName,TeamId,FirstName,LastName,FullName,CountryCode,Position,ClassifiedPosition,Q1,Q2,Q3,Time,Best_Q,delta_to_pole
63,G RUSSELL,RUS,russell,Mercedes,mercedes,George,Russell,George Russell,,1.0,,79.507,78.934,78.518,NaT,78.518,0.000
12,K ANTONELLI,ANT,antonelli,Mercedes,mercedes,Kimi,Antonelli,Kimi Antonelli,,2.0,,80.120,79.435,78.811,NaT,78.811,0.293
6,I HADJAR,HAD,hadjar,Red Bull Racing,red_bull,Isack,Hadjar,Isack Hadjar,,3.0,,80.023,79.653,79.303,NaT,79.303,0.785
16,C LECLERC,LEC,leclerc,Ferrari,ferrari,Charles,Leclerc,Charles Leclerc,,4.0,,80.226,79.357,79.327,NaT,79.327,0.809
81,O PIASTRI,PIA,piastri,McLaren,mclaren,Oscar,Piastri,Oscar Piastri,,5.0,,79.664,79.525,79.380,NaT,79.380,0.862
1,L NORRIS,NOR,norris,McLaren,mclaren,Lando,Norris,Lando Norris,,6.0,,80.010,79.882,79.475,NaT,79.475,0.957
44,L HAMILTON,HAM,hamilton,Ferrari,ferrari,Lewis,Hamilton,Lewis Hamilton,,7.0,,79.811,79.921,79.478,NaT,79.478,0.960
30,L LAWSON,LAW,lawson,Racing Bulls,rb,Liam,Lawson,Liam Lawson,,8.0,,80.491,80.144,79.994,NaT,79.994,1.476
41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,rb,Arvid,Lindblad,Arvid Lindblad,,9.0,,80.409,79.971,81.247,NaT,81.247,2.729
5,G BORTOLETO,BOR,bortoleto,Audi,audi,Gabriel,Bortoleto,Gabriel Bortoleto,,10.0,,80.495,80.221,NaN,NaT,80.221,1.703
27,N HULKENBERG,HUL,hulkenberg,Audi,audi,Nico,Hulkenberg,Nico Hulkenberg,,11.0,,81.024,80.303,NaN,NaT,80.303,1.785
87,O BEARMAN,BEA,bearman,Haas F1 Team,haas,Oliver,Bearman,Oliver Bearman,,12.0,,81.247,80.311,NaN,NaT,80.311,1.793
31,E OCON,OCO,ocon,Haas F1 Team,haas,Esteban,Ocon,Esteban Ocon,,13.0,,80.759,80.491,NaN,NaT,80.491,1.973
10,P GASLY,GAS,gasly,Alpine,alpine,Pierre,Gasly,Pierre Gasly,,14.0,,81.138,80.501,NaN,NaT,80.501,1.983
23,A ALBON,ALB,albon,Williams,williams,Alexander,Albon,Alexander Albon,,15.0,,81.051,80.941,NaN,NaT,80.941,2.423
43,F COLAPINTO,COL,colapinto,Alpine,alpine,Franco,Colapinto,Franco Colapinto,,16.0,,81.200,81.270,NaN,NaT,81.270,2.752
14,F ALONSO,ALO,alonso,Aston Martin,aston_martin,Fernando,Alonso,Fernando Alonso,,17.0,,81.969,NaN,NaN,NaT,81.969,3.451
11,S PEREZ,PER,perez,Cadillac,cadillac,Sergio,Perez,Sergio Perez,,18.0,,82.605,NaN,NaN,NaT,82.605,4.087
77,V BOTTAS,BOT,bottas,Cadillac,cadillac,Valtteri,Bottas,Valtteri Bottas,,19.0,,83.244,NaN,NaN,NaT,83.244,4.726
18,L STROLL,STR,nan,Aston Martin,nan,Lance,Stroll,Lance Stroll,,NaN,,NaN,NaN,NaN,NaT,NaN,NaN
3,M VERSTAPPEN,VER,nan,Red Bull Racing,nan,Max,Verstappen,Max Verstappen,,NaN,,NaN,NaN,NaN,NaT,NaN,NaN
55,C SAINZ,SAI,nan,Williams,nan,Carlos,Sainz,Carlos Sainz,,NaN,,NaN,NaN,NaN,NaT,NaN,NaN

In [6]:
r_laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,3836.437,NOR,1,96.458,1.0,1.0,NaN,18.163,38.796,NaN,...,True,McLaren,3739.743,2026-03-08 04:03:26.366,1,6.0,False,,False,False
1,3923.781,NOR,1,87.344,2.0,1.0,31.074,18.116,38.154,3867.511,...,True,McLaren,3836.437,2026-03-08 04:05:03.060,1,6.0,False,,False,True
2,4010.644,NOR,1,86.863,3.0,1.0,30.541,18.252,38.070,3954.322,...,True,McLaren,3923.781,2026-03-08 04:06:30.404,1,7.0,False,,False,True
3,4096.501,NOR,1,85.857,4.0,1.0,30.190,18.193,37.474,4040.834,...,True,McLaren,4010.644,2026-03-08 04:07:57.267,1,7.0,False,,False,True
4,4182.074,NOR,1,85.573,5.0,1.0,29.930,17.868,37.775,4126.431,...,True,McLaren,4096.501,2026-03-08 04:09:23.124,1,7.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,8389.241,BEA,87,84.615,53.0,2.0,29.699,17.937,36.979,8334.357,...,True,Haas F1 Team,8304.626,2026-03-08 05:19:31.249,1,7.0,False,,False,True
1003,8473.851,BEA,87,84.610,54.0,2.0,29.965,17.876,36.769,8419.238,...,True,Haas F1 Team,8389.241,2026-03-08 05:20:55.864,1,7.0,False,,False,True
1004,8558.351,BEA,87,84.500,55.0,2.0,29.725,17.930,36.845,8503.608,...,True,Haas F1 Team,8473.851,2026-03-08 05:22:20.474,1,7.0,False,,False,True
1005,8644.790,BEA,87,86.439,56.0,2.0,29.768,17.858,38.813,8588.151,...,True,Haas F1 Team,8558.351,2026-03-08 05:23:44.974,1,7.0,False,,False,True
1006,8731.439,BEA,87,86.649,57.0,2.0,30.005,17.905,38.739,8674.827,...,True,Haas F1 Team,8644.790,2026-03-08 05:25:11.413,1,7.0,False,,False,True

In [7]:
median_pace = r_laps.groupby('Driver')['LapTime'].median()
median_pace = pd.DataFrame(median_pace)
median_pace.to_parquet("/Users/dimkostir/Desktop/Projects/F1/data/processed/median_pace.parquet")
median_pace.reset_index()

   Driver  LapTime
0     ALB  85.3565
1     ALO  87.4750
2     ANT  83.0235
3     BEA  84.6595
4     BOR  84.6950
5     BOT  87.9305
6     COL  85.6330
7     GAS  85.2025
8     HAD  85.4040
9     HAM  83.3170
10    LAW  85.2030
11    LEC  83.1740
12    LIN  84.8630
13    NOR  83.6105
14    OCO  85.2520
15    PER  87.5950
16    RUS  83.0930
17    SAI  85.6980
18    STR  87.4480
19    VER  83.5360

In [8]:
team_dif = r_laps[['Driver', "Team"]].drop_duplicates()

# Perform an inner merge on the 'ID' column
teams_dif = pd.merge(team_dif, median_pace, on='Driver', how='inner')
teams_dif = pd.merge(teams_dif, teams_dif, on = 'Team', how = 'inner')

In [9]:
teams_dif = teams_dif[teams_dif["Driver_x"] != teams_dif["Driver_y"]]
teams_dif["team_dif"] = teams_dif["LapTime_x"] - teams_dif["LapTime_y"]
teams_dif = teams_dif.drop(["Driver_y", "LapTime_y", "LapTime_x"], axis= 1)

teams_dif

   Driver_x             Team  team_dif
2       GAS           Alpine   -0.4305
4       PER         Cadillac   -0.3355
6       ANT         Mercedes   -0.0695
8       ALO     Aston Martin    0.0270
10      LEC          Ferrari   -0.1430
11      STR     Aston Martin   -0.0270
14      ALB         Williams   -0.3415
16      VER  Red Bull Racing   -1.8680
18      LAW     Racing Bulls    0.3400
20      OCO     Haas F1 Team    0.5925
21      LIN     Racing Bulls   -0.3400
23      COL           Alpine    0.4305
25      HAM          Ferrari    0.1430
28      SAI         Williams    0.3415
30      HAD  Red Bull Racing    1.8680
32      RUS         Mercedes    0.0695
34      BOT         Cadillac    0.3355
36      BEA     Haas F1 Team   -0.5925

In [10]:
teams_dif = teams_dif.rename(columns={"Driver_x": "Driver"})
teams_dif.to_parquet("/Users/dimkostir/Desktop/Projects/F1/data/processed/teams_dif.parquet")
teams_dif

   Driver             Team  team_dif
2     GAS           Alpine   -0.4305
4     PER         Cadillac   -0.3355
6     ANT         Mercedes   -0.0695
8     ALO     Aston Martin    0.0270
10    LEC          Ferrari   -0.1430
11    STR     Aston Martin   -0.0270
14    ALB         Williams   -0.3415
16    VER  Red Bull Racing   -1.8680
18    LAW     Racing Bulls    0.3400
20    OCO     Haas F1 Team    0.5925
21    LIN     Racing Bulls   -0.3400
23    COL           Alpine    0.4305
25    HAM          Ferrari    0.1430
28    SAI         Williams    0.3415
30    HAD  Red Bull Racing    1.8680
32    RUS         Mercedes    0.0695
34    BOT         Cadillac    0.3355
36    BEA     Haas F1 Team   -0.5925

Υπολογισμός  στατιστικών ανά Stint ανά οδηγό. Stint = ο αριθμός των γύρων ου κάνει ένας οδηγος με τα ίδια ελαστικά, χωρίς να μπει pit stop. Ξεκινάει από την έξοδο και τελειώνει στην έισοδο στα pit.

Βήμα 1 — Έλεγχος αξιοπιστίας:

Αν το stint έχει λιγότερους από 4 γύρους, επιστρέφει None — δεν υπολογίζει τίποτα. Με λιγότερους από 4 γύρους η κλίση δεν είναι στατιστικά αξιόπιστη γιατί ένας μόνο outlier γύρος θα αλλοιώσει το αποτέλεσμα.

Βήμα 2 — Linear regression:

Χρησιμοποιεί το np.polyfit(TyreLife, LapTime, 1) για να βρει την ευθεία που "ταιριάζει" καλύτερα στα δεδομένα. Το TyreLife είναι ο άξονας x — πόσοι γύροι έχουν γίνει στο τρέχον σετ ελαστικών. Το LapTime είναι ο άξονας y — ο χρόνος γύρου σε δευτερόλεπτα. Το 1 σημαίνει ότι ψάχνει ευθεία γραμμή — όχι καμπύλη.

Βήμα 3 — Εξαγωγή κλίσης:

Το np.polyfit επιστρέφει δύο αριθμούς — κλίση και intercept. Το [0] κρατά μόνο την κλίση. Αυτός ο αριθμός λέει: "για κάθε επιπλέον γύρο στο ίδιο σετ ελαστικών, ο χρόνος ανεβαίνει κατά X δευτερόλεπτα".

Έξοδος: Ένας αριθμός — π.χ. 0.087 σημαίνει ότι ο οδηγός χάνει 0.087 δευτερόλεπτα ανά γύρο λόγω φθοράς ελαστικών.

In [11]:
deg_rate_temp = r_laps.groupby(["Driver", "Stint"]).size()
degradation_rate = r_laps.groupby(["Driver", "Stint"]).count()
degradation_rate["Stint_Laps"] = degradation_rate["DriverNumber"]
r_laps[r_laps["Driver"] == "ALB"][["Driver", "Stint", "TyreLife", "LapTime"]].head(20)

    Driver  Stint  TyreLife  LapTime
351    ALB    1.0       1.0   99.376
352    ALB    1.0       2.0   87.780
353    ALB    1.0       3.0   87.512
354    ALB    1.0       4.0   87.911
355    ALB    1.0       5.0   87.176
356    ALB    1.0       6.0   86.436
357    ALB    1.0       7.0   85.688
358    ALB    1.0       8.0   85.558
359    ALB    1.0       9.0   85.728
360    ALB    1.0      10.0   86.030
364    ALB    2.0       2.0   85.379
365    ALB    2.0       3.0   85.035
366    ALB    2.0       4.0   88.434
367    ALB    2.0       5.0   85.662
370    ALB    2.0       8.0   85.041
371    ALB    2.0       9.0   85.065
372    ALB    2.0      10.0   85.297
373    ALB    2.0      11.0   85.258
374    ALB    2.0      12.0   85.334
375    ALB    2.0      13.0   85.569

In [12]:
def calc_deg_rate(stint_df):
    stint_df = stint_df[stint_df["TyreLife"] > 1]  # αφαίρεσε πρώτο γύρο
    stint_df = stint_df[stint_df["Stint"] > 1]
    if len(stint_df) < 4:                           # έλεγξε αν έμειναν αρκετοί
        return None
    slope = np.polyfit(stint_df["TyreLife"], stint_df["LapTime"], 1)[0]
    return slope

degradation_rate = r_laps.groupby(["Driver", "Stint"]).apply(calc_deg_rate)
degradation_rate = pd.DataFrame(degradation_rate)
degradation_rate = degradation_rate.reset_index()
degradation_rate["Deg_Rate"] = degradation_rate[0]
degradation_rate = degradation_rate.drop([0], axis = 1)
degradation_rate

/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_2870/1766406032.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  degradation_rate = r_laps.groupby(["Driver", "Stint"]).apply(calc_deg_rate)

   Driver  Stint  Deg_Rate
0     ALB    1.0       NaN
1     ALB    2.0  0.037991
2     ALB    3.0  0.016139
3     ALO    1.0       NaN
4     ALO    3.0  0.353250
5     ANT    1.0       NaN
6     ANT    2.0 -0.013633
7     BEA    1.0       NaN
8     BEA    2.0  0.013921
9     BOR    1.0       NaN
10    BOR    2.0 -0.058137
11    BOR    3.0  0.048332
12    BOT    1.0       NaN
13    BOT    2.0       NaN
14    COL    1.0       NaN
15    COL    2.0  0.017346
16    COL    3.0  0.112667
17    GAS    1.0       NaN
18    GAS    2.0  0.005497
19    HAD    1.0       NaN
20    HAM    1.0       NaN
21    HAM    2.0 -0.022561
22    LAW    1.0       NaN
23    LAW    2.0 -0.072421
24    LAW    3.0  0.031556
25    LEC    1.0       NaN
26    LEC    2.0 -0.002770
27    LIN    1.0       NaN
28    LIN    2.0  0.023843
29    NOR    1.0       NaN
30    NOR    2.0  0.013996
31    NOR    3.0 -0.036832
32    OCO    1.0       NaN
33    OCO    2.0 -0.002651
34    PER    1.0       NaN
35    PER    2.0  0.018975
36    PER    3.0  0.194209
37    RUS    1.0       NaN
38    RUS    2.0  0.000661
39    SAI    1.0       NaN
40    SAI    2.0  0.148359
41    SAI    3.0  0.045212
42    SAI    4.0 -0.582588
43    STR    1.0       NaN
44    STR    2.0  0.099795
45    STR    3.0  0.085486
46    STR    4.0       NaN
47    STR    5.0       NaN
48    VER    1.0       NaN
49    VER    2.0  0.035650
50    VER    3.0  0.072350

Weighted Average

In [13]:
stint_sizes = r_laps.groupby(["Driver", "Stint"]).size().reset_index()
stint_sizes = stint_sizes.rename(columns={0: "Laps"})
merged_df = pd.merge(stint_sizes, degradation_rate, on=['Driver','Stint'], how='inner')
merged_df

   Driver  Stint  Laps  Deg_Rate
0     ALB    1.0    10       NaN
1     ALB    2.0    17  0.037991
2     ALB    3.0    23  0.016139
3     ALO    1.0    10       NaN
4     ALO    3.0     7  0.353250
5     ANT    1.0    10       NaN
6     ANT    2.0    40 -0.013633
7     BEA    1.0    14       NaN
8     BEA    2.0    36  0.013921
9     BOR    1.0    14       NaN
10    BOR    2.0    13 -0.058137
11    BOR    3.0    23  0.048332
12    BOT    1.0    10       NaN
13    BOT    2.0     2       NaN
14    COL    1.0     8       NaN
15    COL    2.0    28  0.017346
16    COL    3.0     9  0.112667
17    GAS    1.0    10       NaN
18    GAS    2.0    40  0.005497
19    HAD    1.0    10       NaN
20    HAM    1.0    21       NaN
21    HAM    2.0    28 -0.022561
22    LAW    1.0    10       NaN
23    LAW    2.0    17 -0.072421
24    LAW    3.0    23  0.031556
25    LEC    1.0    18       NaN
26    LEC    2.0    31 -0.002770
27    LIN    1.0    13       NaN
28    LIN    2.0    36  0.023843
29    NOR    1.0    10       NaN
30    NOR    2.0    17  0.013996
31    NOR    3.0    23 -0.036832
32    OCO    1.0    10       NaN
33    OCO    2.0    40 -0.002651
34    PER    1.0    14       NaN
35    PER    2.0    21  0.018975
36    PER    3.0    11  0.194209
37    RUS    1.0    11       NaN
38    RUS    2.0    40  0.000661
39    SAI    1.0    10       NaN
40    SAI    2.0    17  0.148359
41    SAI    3.0    10  0.045212
42    SAI    4.0    10 -0.582588
43    STR    1.0    10       NaN
44    STR    2.0     9  0.099795
45    STR    3.0     5  0.085486
46    STR    4.0     3       NaN
47    STR    5.0     3       NaN
48    VER    1.0    13       NaN
49    VER    2.0    20  0.035650
50    VER    3.0    16  0.072350

In [14]:
merged_df_clean = merged_df[merged_df["Deg_Rate"].notna()]

deg_rate_final = merged_df_clean.groupby("Driver").apply(
    lambda x: (x["Deg_Rate"] * x["Laps"]).sum() / x["Laps"].sum()
).reset_index()

deg_rate_final = deg_rate_final.rename(columns={0: "Deg_Rate_Weighted"})
deg_rate_final

/var/folders/s0/k6p2569n6w1br5pz86sgwm400000gn/T/ipykernel_2870/3561516797.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  deg_rate_final = merged_df_clean.groupby("Driver").apply(

   Driver  Deg_Rate_Weighted
0     ALB           0.025426
1     ALO           0.353250
2     ANT          -0.013633
3     BEA           0.013921
4     BOR           0.009885
5     COL           0.040532
6     GAS           0.005497
7     HAM          -0.022561
8     LAW          -0.012634
9     LEC          -0.002770
10    LIN           0.023843
11    NOR          -0.015230
12    OCO          -0.002651
13    PER           0.079212
14    RUS           0.000661
15    SAI          -0.077072
16    STR           0.094685
17    VER           0.051961

In [15]:
circuit_location = fastf1.get_event(2026, 1)["Location"]
circuit_location

req         WARNING 	DEFAULT CACHE ENABLED! (7.88 GB) /Users/dimkostir/Library/Caches/fastf1

'Melbourne'

In [16]:
r_results["Driver"] = r_results["Abbreviation"]
r_results.drop(["Abbreviation"], axis =1)
master_table = pd.merge(r_results, deg_rate_final, on=['Driver'], how='left')
master_table = pd.merge(master_table, median_pace, on  =['Driver'], how = 'left')
master_table = pd.merge(master_table, teams_dif, on  =['Driver'], how = 'left')
master_table = pd.merge(master_table, q_results[["Abbreviation", "delta_to_pole", "Position"]], on="Abbreviation", how="left")

master_table = master_table.drop(["CountryCode", "TeamId", "Team", "Abbreviation", "Laps", "Time" ], axis = 1)
master_table["Circuit_Location"] = circuit_location

master_table = master_table.rename(columns={"Position_x": "Finish_Position"})
master_table = master_table.rename(columns={"Position_y": "Qual_Position"})
master_table = master_table.rename(columns={"LapTime": "Median_lap_time"})

master_table.to_csv('/Users/dimkostir/Desktop/Projects/F1/data/csv/master_table_01.csv')
master_table.to_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/master_table_01.parquet')
master_table

,TeamName,FullName,Finish_Position,ClassifiedPosition,GridPosition,Status,Points,Driver,Deg_Rate_Weighted,Median_lap_time,team_dif,delta_to_pole,Qual_Position,Circuit_Location
0,Mercedes,George Russell,1.0,1,1.0,Finished,25.0,RUS,0.000661,83.0930,0.0695,0.000,1.0,Melbourne
1,Mercedes,Kimi Antonelli,2.0,2,2.0,Finished,18.0,ANT,-0.013633,83.0235,-0.0695,0.293,2.0,Melbourne
2,Ferrari,Charles Leclerc,3.0,3,4.0,Finished,15.0,LEC,-0.002770,83.1740,-0.1430,0.809,4.0,Melbourne
3,Ferrari,Lewis Hamilton,4.0,4,7.0,Finished,12.0,HAM,-0.022561,83.3170,0.1430,0.960,7.0,Melbourne
4,McLaren,Lando Norris,5.0,5,6.0,Finished,10.0,NOR,-0.015230,83.6105,NaN,0.957,6.0,Melbourne
5,Red Bull Racing,Max Verstappen,6.0,6,20.0,Finished,8.0,VER,0.051961,83.5360,-1.8680,NaN,NaN,Melbourne
6,Haas F1 Team,Oliver Bearman,7.0,7,12.0,Lapped,6.0,BEA,0.013921,84.6595,-0.5925,1.793,12.0,Melbourne
7,Racing Bulls,Arvid Lindblad,8.0,8,9.0,Lapped,4.0,LIN,0.023843,84.8630,-0.3400,2.729,9.0,Melbourne
8,Audi,Gabriel Bortoleto,9.0,9,10.0,Lapped,2.0,BOR,0.009885,84.6950,NaN,1.703,10.0,Melbourne
9,Alpine,Pierre Gasly,10.0,10,14.0,Lapped,1.0,GAS,0.005497,85.2025,-0.4305,1.983,14.0,Melbourne
10,Haas F1 Team,Esteban Ocon,11.0,11,13.0,Lapped,0.0,OCO,-0.002651,85.2520,0.5925,1.973,13.0,Melbourne
11,Williams,Alexander Albon,12.0,12,15.0,Lapped,0.0,ALB,0.025426,85.3565,-0.3415,2.423,15.0,Melbourne
12,Racing Bulls,Liam Lawson,13.0,13,8.0,Lapped,0.0,LAW,-0.012634,85.2030,0.3400,1.476,8.0,Melbourne
13,Alpine,Franco Colapinto,14.0,14,16.0,Lapped,0.0,COL,0.040532,85.6330,0.4305,2.752,16.0,Melbourne
14,Williams,Carlos Sainz,15.0,15,21.0,Lapped,0.0,SAI,-0.077072,85.6980,0.3415,NaN,NaN,Melbourne
15,Cadillac,Sergio Perez,16.0,16,18.0,Lapped,0.0,PER,0.079212,87.5950,-0.3355,4.087,18.0,Melbourne
16,Aston Martin,Lance Stroll,17.0,R,22.0,Lapped,0.0,STR,0.094685,87.4480,-0.0270,NaN,NaN,Melbourne
17,Aston Martin,Fernando Alonso,18.0,R,17.0,Retired,0.0,ALO,0.353250,87.4750,0.0270,3.451,17.0,Melbourne
18,Cadillac,Valtteri Bottas,19.0,R,19.0,Retired,0.0,BOT,NaN,87.9305,0.3355,4.726,19.0,Melbourne
19,Red Bull Racing,Isack Hadjar,20.0,R,3.0,Retired,0.0,HAD,NaN,85.4040,1.8680,0.785,3.0,Melbourne
20,McLaren,Oscar Piastri,21.0,W,5.0,Did not start,0.0,PIA,NaN,NaN,NaN,0.862,5.0,Melbourne
21,Audi,Nico Hulkenberg,22.0,W,11.0,Did not start,0.0,HUL,NaN,NaN,NaN,1.785,11.0,Melbourne

In [19]:
MASTERRR = pd.read_parquet('/Users/dimkostir/Desktop/Projects/F1/data/processed/master_tables/master_table_24_25.parquet')
MASTERRR.to_csv('/Users/dimkostir/Desktop/Projects/F1/mast.csv')
MASTERRR

,Driver,TeamName_x,GridPosition,Finish_Position,Status,Median_lap_time,team_dif,Deg_Rate_Weighted,delta_to_pole,Qual_Position,Year,Location
0,VER,Red Bull Racing,1.0,1.0,Finished,95.4095,-0.8015,0.046802,0.000,1.0,2024,Sakhir
1,PER,Red Bull Racing,5.0,2.0,Finished,96.2110,0.8015,0.041648,0.358,5.0,2024,Sakhir
2,SAI,Ferrari,4.0,3.0,Finished,96.1040,-0.6520,0.031205,0.328,4.0,2024,Sakhir
3,LEC,Ferrari,2.0,4.0,Finished,96.7560,0.6520,0.033499,0.228,2.0,2024,Sakhir
4,RUS,Mercedes,3.0,5.0,Finished,96.4400,-0.1930,0.021189,0.306,3.0,2024,Sakhir
...,...,...,...,...,...,...,...,...,...,...,...,...
953,ALB,Williams,17.0,16.0,Finished,89.7575,-0.0990,0.036674,1.209,17.0,2025,Yas Island
954,HAD,Racing Bulls,9.0,17.0,Lapped,90.1420,0.3800,-0.012666,0.865,9.0,2025,Yas Island
955,LAW,Racing Bulls,13.0,18.0,Lapped,89.7620,-0.3800,0.001090,0.870,13.0,2025,Yas Island
956,GAS,Alpine,19.0,19.0,Lapped,89.9080,0.0610,0.050974,1.261,19.0,2025,Yas Island
957,COL,Alpine,20.0,20.0,Lapped,89.8470,-0.0610,0.078744,1.683,20.0,2025,Yas Island